channels:
  - conda-forge
dependencies:
  - python>=3.8
  - conda
  - networkx
  - rich
  - click
  - fsspec
  - requests
  - aiohttp
  - pydantic
  - yaml
  # development
  - mypy
  - flake8
  - black
  - isort
  - pytest
  - pytest-cov
  - pre-commit