channels:
  - conda-forge
dependencies:
  # production
  - python=3.8
  - networkx
  - conda
  - conda-build
  # development
  - mypy
  - flake8
  - black
  - isort
  - pytest
  - pytest-cov
  - pre-commit