dependencies:
  # Production
  - python =3.8
  - networkx
  - conda
  - conda-build
  # Development
  - flake8
  - types-requests
  - black
  - mypy
  - pytest
  - pytest-cov
  - pre-commit
  - isort
