[tool.isort]
profile = "black"


[tool.mypy]
mypy_path = "src"
ignore_missing_imports = false
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "conda.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "networkx.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "ruamel.*"
ignore_missing_imports = true


[tool.pytest.ini_options]
addopts = [
    "--strict-markers",
    "--strict-config",
    "-ra",
]
testpaths = "tests"
markers = [
    "slow: integration tests with long execution time"
]
filterwarnings = [
    "ignore::DeprecationWarning:conda.*"
]
